version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies:actions"
    groups:
      codeql-actions:
        patterns:
          - "github/codeql-action*"
      github-actions:
        patterns:
          - "*"
        exclude-patterns:
          - "github/codeql-action*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies:java"
    groups:
      java-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/fogwall-dashboard/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies:frontend"
    groups:
      frontend-npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies:docker"
