package com.rbc.fogwall.git;

import com.rbc.fogwall.config.ContentPatternConfig;
import com.rbc.fogwall.db.model.PushStep;
import com.rbc.fogwall.db.model.StepStatus;
import com.rbc.fogwall.validation.ContentPatternBundleResolver;
import com.rbc.fogwall.validation.ContentPatternFinding;
import com.rbc.fogwall.validation.PatternBundleScanner;
import java.util.Collection;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.eclipse.jgit.transport.ReceiveCommand;
import org.eclipse.jgit.transport.ReceivePack;

/**
 * S&amp;F-mode content-pattern scanning of the pushed diff (structured PII/identifier detection - SIN, SSN, NINO, etc).
 * Scans the aggregate diff already generated by {@link DiffGenerationHook}.
 *
 * <p>Always WARN, never blocks - see {@link ContentPatternConfig}. Matched values are routed through
 * {@link PushContext#addSecretsToRedact} so they never persist unredacted in the stored diff, same as
 * {@link SecretScanningHook} findings.
 */
@RequiredArgsConstructor
public class ContentPatternDiffHook implements FogwallHook {

    private static final int ORDER = 345;
    static final String STEP_NAME = "scanContentPatternsDiff";

    private final ContentPatternConfig config;
    private final PushContext pushContext;

    @Override
    public void onPreReceive(ReceivePack rp, Collection<ReceiveCommand> commands) {
        if (!config.isEnabled() || !config.isScanDiff()) {
            pushContext.addStep(PushStep.builder()
                    .stepName(STEP_NAME)
                    .stepOrder(ORDER)
                    .status(StepStatus.SKIPPED)
                    .build());
            return;
        }

        String aggregateDiff = pushContext
                .getStepContent(DiffGenerationHook.STEP_NAME_PUSH_DIFF)
                .orElse(null);
        if (aggregateDiff == null || aggregateDiff.isBlank()) {
            pushContext.addStep(PushStep.builder()
                    .stepName(STEP_NAME)
                    .stepOrder(ORDER)
                    .status(StepStatus.PASS)
                    .build());
            return;
        }

        var scanner = new PatternBundleScanner(ContentPatternBundleResolver.resolve(config));
        List<ContentPatternFinding> findings = scanner.scan(aggregateDiff);
        ContentPatternStepRecorder.record(pushContext, STEP_NAME, ORDER, findings);
    }

    @Override
    public int getOrder() {
        return ORDER;
    }

    @Override
    public String getName() {
        return "ContentPatternDiffHook";
    }
}
