package com.rbc.fogwall.git;

import com.rbc.fogwall.config.DiffScanConfig;
import com.rbc.fogwall.db.model.PushStep;
import com.rbc.fogwall.db.model.StepStatus;
import com.rbc.fogwall.validation.BlockedContentDiffCheck;
import com.rbc.fogwall.validation.Violation;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.lib.Repository;
import org.eclipse.jgit.transport.ReceiveCommand;
import org.eclipse.jgit.transport.ReceivePack;

/**
 * Pre-receive hook that scans push content for blocked literals and patterns.
 *
 * <p>Two scan passes run per push:
 *
 * <ol>
 *   <li><b>Aggregate scan</b> — re-uses the unified diff already stored in {@link PushContext} by
 *       {@link DiffGenerationHook}. Catches content that is present in the net result of the push.
 *   <li><b>Per-commit scan</b> — for pushes containing more than one commit, generates an independent diff for each
 *       consecutive commit pair and scans it separately. This closes the intermediate-commit bypass: a secret
 *       introduced in commit B and removed in commit C produces a clean aggregate diff (A→C) but is caught by the
 *       B-scoped diff (A→B).
 * </ol>
 *
 * <p>Only added lines (those prefixed with {@code +} in the unified diff) are scanned — deletions and context lines are
 * ignored. Per-commit violations include the short SHA in their detail so reviewers can identify which commit triggered
 * the finding.
 */
@Slf4j
@RequiredArgsConstructor
public class DiffScanningHook implements FogwallHook {

    private static final int ORDER = 300;
    private static final String STEP_NAME = "scanDiff";

    private final DiffScanConfig diffScanConfig;
    private final ValidationContext validationContext;
    private final PushContext pushContext;

    @Override
    public void onPreReceive(ReceivePack rp, Collection<ReceiveCommand> commands) {
        List<String> logs = new ArrayList<>();
        boolean anyFailed = false;

        // Pass 1: aggregate scan using the diff already generated by DiffGenerationHook
        String aggregateDiff = pushContext
                .getStepContent(DiffGenerationHook.STEP_NAME_PUSH_DIFF)
                .orElse(null);
        if (aggregateDiff == null || aggregateDiff.isBlank()) {
            log.debug("No aggregate diff available for scanning - skipping aggregate pass");
        } else {
            List<Violation> violations = runCheck(aggregateDiff);
            if (!violations.isEmpty()) {
                for (Violation v : violations) {
                    validationContext.addIssue(STEP_NAME, v.reason(), v.formattedDetail());
                    logs.add("FAIL: aggregate: " + v.reason());
                }
                anyFailed = true;
            } else {
                logs.add("PASS: aggregate diff");
            }
        }

        // Pass 2: per-commit scan — catches content introduced in intermediate commits
        Repository repo = rp.getRepository();
        for (ReceiveCommand cmd : commands) {
            if (cmd.getType() == ReceiveCommand.Type.DELETE) {
                continue;
            }
            if (cmd.getRefName().startsWith("refs/tags/")) {
                continue;
            }

            String effectiveFrom = pushContext.getEffectiveFromId(cmd.getRefName());
            boolean hasNonZeroEffectiveBase = effectiveFrom != null && !effectiveFrom.matches("^0+$");
            String baseCommit =
                    hasNonZeroEffectiveBase ? effectiveFrom : cmd.getOldId().name();
            String tipCommit = cmd.getNewId().name();

            try {
                List<Commit> commits = CommitInspectionService.getCommitRange(repo, baseCommit, tipCommit);

                // Single-commit push: aggregate scan already covers it exactly
                if (commits.size() <= 1) {
                    continue;
                }

                // getCommitRange returns newest-first; reverse for chronological traversal
                Collections.reverse(commits);

                for (Commit commit : commits) {
                    String parent = commit.getParent() != null ? commit.getParent() : baseCommit;
                    String shortSha = commit.getSha().substring(0, 7);
                    try {
                        String perCommitDiff = CommitInspectionService.getFormattedDiff(repo, parent, commit.getSha());
                        List<Violation> violations = runCheck(perCommitDiff);
                        if (violations.isEmpty()) {
                            logs.add("PASS: " + shortSha);
                        } else {
                            for (Violation v : violations) {
                                String reason = shortSha + ": " + v.reason();
                                String detail = "commit " + shortSha + ": " + v.formattedDetail();
                                validationContext.addIssue(STEP_NAME, reason, detail);
                                logs.add("FAIL: " + reason);
                            }
                            anyFailed = true;
                        }
                    } catch (IOException e) {
                        log.warn("Per-commit diff failed for {}, skipping", commit.getSha(), e);
                        logs.add("WARN: " + shortSha + " - diff failed, skipped");
                    }
                }
            } catch (IOException | GitAPIException e) {
                log.warn("Could not enumerate commits for per-commit scan on {}", cmd.getRefName(), e);
            }
        }

        if (!anyFailed) {
            pushContext.addStep(PushStep.builder()
                    .stepName(STEP_NAME)
                    .stepOrder(ORDER)
                    .status(StepStatus.PASS)
                    .logs(logs)
                    .build());
        }
    }

    private List<Violation> runCheck(String diff) {
        if (diff == null || diff.isBlank()) {
            return List.of();
        }
        BlockedContentDiffCheck check = new BlockedContentDiffCheck(diffScanConfig.getBlock());
        return check.check(diff).orElse(List.of());
    }

    @Override
    public int getOrder() {
        return ORDER;
    }

    @Override
    public String getName() {
        return "DiffScanningHook";
    }
}
