#!/usr/bin/env bash
# Generates a throw-away SSH keypair and registers the public key with the
# Gitea test-user account. Run this once after docker/gitea-setup.sh.
#
# The private key path is written to test/gitea/tokens.env as SSH_TEST_KEY_PATH.
# Add the public key to fogwall either:
#   - via the profile page (SSH Keys tab) after starting the dashboard, or
#   - by adding it to fogwall-local.yml under the dev user's ssh-keys: list.
#
# Usage:
#   bash docker/gitea-ssh-setup.sh
#   GITEA_URL=http://localhost:3000 bash docker/gitea-ssh-setup.sh
set -euo pipefail

GITEA_URL="${GITEA_URL:-http://localhost:3000}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TOKENS_FILE="${REPO_ROOT}/test/gitea/tokens.env"
KEY_PATH="${REPO_ROOT}/test/gitea/test_ed25519"

if [[ ! -f "${TOKENS_FILE}" ]]; then
    echo "ERROR: ${TOKENS_FILE} not found — run docker/gitea-setup.sh first" >&2
    exit 1
fi
# shellcheck source=/dev/null
source "${TOKENS_FILE}"

if [[ -z "${GITEA_TESTUSER_TOKEN:-}" ]]; then
    echo "ERROR: GITEA_TESTUSER_TOKEN not set in tokens.env" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Generate keypair
# ---------------------------------------------------------------------------

if [[ -f "${KEY_PATH}" ]]; then
    echo "==> SSH key already exists at ${KEY_PATH}, skipping generation"
else
    echo "==> Generating SSH keypair..."
    ssh-keygen -t ed25519 -C "fogwall-test@local" -N "" -f "${KEY_PATH}" -q
    chmod 600 "${KEY_PATH}"
    echo "    ${KEY_PATH}"
    echo "    ${KEY_PATH}.pub"
fi

PUB_KEY="$(cat "${KEY_PATH}.pub")"

# ---------------------------------------------------------------------------
# Generate local SSH config (gitignored) and write key path to tokens.env.
# Do this before the Gitea API call so the env is set even if registration fails.
# ---------------------------------------------------------------------------

SSH_CONFIG="${REPO_ROOT}/test/gitea/ssh_config"

cat > "${SSH_CONFIG}" <<EOF
# Local SSH config for fogwall smoke tests.
# Do not commit — this file is gitignored.
# Use via: GIT_SSH_COMMAND="ssh -F ${SSH_CONFIG}" git push ...
Host localhost
    ForwardAgent yes
    AddKeysToAgent yes
    IdentityFile ${KEY_PATH}
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
EOF

if grep -q 'SSH_TEST_KEY_PATH' "${TOKENS_FILE}"; then
    sed -i "s|^export SSH_TEST_KEY_PATH=.*|export SSH_TEST_KEY_PATH=\"${KEY_PATH}\"|" "${TOKENS_FILE}"
else
    printf '\n# SSH test key (generated by docker/gitea-ssh-setup.sh)\nexport SSH_TEST_KEY_PATH="%s"\n' \
        "${KEY_PATH}" >> "${TOKENS_FILE}"
fi

# ---------------------------------------------------------------------------
# Register with Gitea (test-user account)
# ---------------------------------------------------------------------------

echo "==> Registering public key with Gitea test-user..."

existing=$(curl -sf \
    -H "Authorization: token ${GITEA_TESTUSER_TOKEN}" \
    "${GITEA_URL}/api/v1/user/keys" | grep -c '"title":"fogwall-test"' || true)

if [[ "${existing}" -gt 0 ]]; then
    echo "    Already registered, skipping"
else
    http_code=$(curl -s -o /dev/null -w "%{http_code}" \
        -H "Authorization: token ${GITEA_TESTUSER_TOKEN}" \
        -H "Content-Type: application/json" \
        "${GITEA_URL}/api/v1/user/keys" \
        -X POST \
        -d "{\"key\": \"${PUB_KEY}\", \"title\": \"fogwall-test\", \"read_only\": false}")
    if [[ "${http_code}" == "201" ]]; then
        echo "    Registered"
    elif [[ "${http_code}" == "422" ]]; then
        echo "    Already registered in Gitea (duplicate), skipping"
    else
        echo "ERROR: Gitea key registration failed (HTTP ${http_code})" >&2
        exit 1
    fi
fi

echo ""
echo "==> Done. Public key:"
echo "    ${PUB_KEY}"
echo ""
echo "    Add it to fogwall via the profile page (SSH Keys tab) or fogwall-local.yml:"
echo "      users:"
echo "        - username: dev"
echo "          ssh-keys:"
echo "            - public-key: \"${PUB_KEY}\""
echo ""
echo "    Then push with:"
echo "      source test/gitea/env.sh"
echo "      GIT_SSH_COMMAND=\"ssh -F ${SSH_CONFIG}\" git push <remote> <branch>"
echo ""
echo "    The generated ssh_config (${SSH_CONFIG}) sets ForwardAgent, AddKeysToAgent,"
echo "    and IdentityFile — no need to edit ~/.ssh/config or run ssh-add manually."
