package com.rbc.fogwall.crypto;

import java.nio.file.Path;
import java.util.Optional;
import lombok.extern.slf4j.Slf4j;

/**
 * Resolves the {@link TokenCipher} used to encrypt SCM OAuth tokens at rest (#40), without ever failing startup.
 *
 * <p>A missing or invalid {@code token-encryption-key-path} disables OAuth account <em>linking</em> only — it never
 * touches push authorization. {@code CheckUserPushPermissionHook}'s strict-mode check reads only the plaintext
 * {@code verified} column on {@code user_scm_identities} and never consults this class or {@code user_scm_tokens}, so a
 * key problem cannot silently downgrade strict mode to permissive.
 */
@Slf4j
public class TokenCipherProvider {

    private final TokenCipher cipher;
    private final boolean autoGenerated;

    private TokenCipherProvider(TokenCipher cipher, boolean autoGenerated) {
        this.cipher = cipher;
        this.autoGenerated = autoGenerated;
    }

    /**
     * @param configuredKeyPath value of {@code scm-oauth.token-encryption-key-path}, or blank/null if unset
     * @param defaultKeyPath local-devex fallback location used only when {@code configuredKeyPath} is unset (e.g.
     *     {@code ./.data/scm-oauth-token-key}, mirroring the {@code database.path} default-directory convention)
     */
    public static TokenCipherProvider initialize(String configuredKeyPath, Path defaultKeyPath) {
        try {
            if (configuredKeyPath != null && !configuredKeyPath.isBlank()) {
                byte[] key = AesGcmTokenCipher.loadKeyFromFile(Path.of(configuredKeyPath));
                return new TokenCipherProvider(new AesGcmTokenCipher(key), false);
            }
            byte[] key = AesGcmTokenCipher.loadOrGenerateKeyFile(defaultKeyPath);
            log.warn(
                    "SCM OAuth token encryption key is AUTO-GENERATED at '{}' because 'scm-oauth.token-encryption-key-path' "
                            + "is not configured. This is fine for local development only. Production deployments MUST set "
                            + "'scm-oauth.token-encryption-key-path' to a durable, backed-up location — the auto-generated file "
                            + "may not survive a container restart/redeploy, and losing it requires every linked user to "
                            + "re-link their SCM account (push authorization is unaffected either way).",
                    defaultKeyPath);
            return new TokenCipherProvider(new AesGcmTokenCipher(key), true);
        } catch (Exception e) {
            log.error(
                    "SCM OAuth token encryption key is UNAVAILABLE ({}). OAuth account linking (link/callback endpoints) "
                            + "is DISABLED until this is fixed. Push authorization, including strict identity mode, is NOT "
                            + "affected — it reads only the already-verified 'user_scm_identities.verified' flag.",
                    e.getMessage(),
                    e);
            return new TokenCipherProvider(null, false);
        }
    }

    public Optional<TokenCipher> cipher() {
        return Optional.ofNullable(cipher);
    }

    public boolean isAvailable() {
        return cipher != null;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }
}
