apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fogwall.fullname" . }}
  labels:
    {{- include "fogwall.labels" . | nindent 4 }}
data:
  fogwall-{{ .Values.configProfileName }}.yml: |
{{ .Values.config | indent 4 }}
