package com.rbc.fogwall.crypto;

import static org.junit.jupiter.api.Assertions.*;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.SecureRandom;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class TokenCipherProviderTest {

    @TempDir
    Path tempDir;

    @Test
    void availableAndNotAutoGeneratedWhenKeyConfigured() {
        byte[] key = new byte[32];
        new SecureRandom().nextBytes(key);

        var provider = TokenCipherProvider.initialize(Optional.of(key), tempDir.resolve("unused-default"));

        assertTrue(provider.isAvailable());
        assertFalse(provider.isAutoGenerated());
        assertFalse(Files.exists(tempDir.resolve("unused-default")));
    }

    @Test
    void configuredKeyOfWrongLength_failsRatherThanDisablingLinking() {
        Path defaultPath = tempDir.resolve("unused-default");

        assertThrows(
                IllegalArgumentException.class,
                () -> TokenCipherProvider.initialize(Optional.of(new byte[16]), defaultPath));
    }

    @Test
    void autoGeneratesAndPersistsWhenNoKeyConfigured() {
        Path defaultPath = tempDir.resolve("auto-key");

        var provider = TokenCipherProvider.initialize(Optional.empty(), defaultPath);

        assertTrue(provider.isAvailable());
        assertTrue(provider.isAutoGenerated());
        assertTrue(Files.exists(defaultPath));
    }

    @Test
    void corruptAutoGeneratedKey_disablesLinkingWithoutFailing() throws Exception {
        Path defaultPath = tempDir.resolve("auto-key");
        Files.writeString(defaultPath, "not a key");

        var provider = TokenCipherProvider.initialize(Optional.empty(), defaultPath);

        assertFalse(provider.isAvailable());
        assertTrue(provider.cipher().isEmpty());
    }

    @Test
    void reusesAutoGeneratedKeyAcrossRestarts() {
        Path defaultPath = tempDir.resolve("auto-key");

        var first = TokenCipherProvider.initialize(Optional.empty(), defaultPath);
        byte[] blob = first.cipher().orElseThrow().encrypt("secret".getBytes(StandardCharsets.UTF_8));

        var second = TokenCipherProvider.initialize(Optional.empty(), defaultPath);
        byte[] decrypted = second.cipher().orElseThrow().decrypt(blob);

        assertEquals("secret", new String(decrypted, StandardCharsets.UTF_8));
    }
}
