package com.rbc.fogwall.crypto;

import static org.junit.jupiter.api.Assertions.*;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.SecureRandom;
import java.util.Base64;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class TokenCipherProviderTest {

    @TempDir
    Path tempDir;

    @Test
    void availableAndNotAutoGeneratedWhenConfiguredKeyIsValid() throws Exception {
        Path keyFile = tempDir.resolve("configured-key");
        byte[] key = new byte[32];
        new SecureRandom().nextBytes(key);
        Files.writeString(keyFile, Base64.getEncoder().encodeToString(key));

        var provider = TokenCipherProvider.initialize(keyFile.toString(), tempDir.resolve("unused-default"));

        assertTrue(provider.isAvailable());
        assertFalse(provider.isAutoGenerated());
    }

    @Test
    void unavailableWhenConfiguredKeyPathDoesNotExist() {
        var provider = TokenCipherProvider.initialize(
                tempDir.resolve("does-not-exist").toString(), tempDir.resolve("unused-default"));

        assertFalse(provider.isAvailable());
        assertTrue(provider.cipher().isEmpty());
    }

    @Test
    void unavailableWhenConfiguredKeyIsCorrupt() throws Exception {
        Path keyFile = tempDir.resolve("bad-key");
        Files.writeString(keyFile, Base64.getEncoder().encodeToString(new byte[16]));

        var provider = TokenCipherProvider.initialize(keyFile.toString(), tempDir.resolve("unused-default"));

        assertFalse(provider.isAvailable());
    }

    @Test
    void autoGeneratesAndPersistsWhenNoPathConfigured() {
        Path defaultPath = tempDir.resolve("auto-key");

        var provider = TokenCipherProvider.initialize(null, defaultPath);

        assertTrue(provider.isAvailable());
        assertTrue(provider.isAutoGenerated());
        assertTrue(Files.exists(defaultPath));
    }

    @Test
    void autoGeneratesAndPersistsWhenPathBlank() {
        Path defaultPath = tempDir.resolve("auto-key");

        var provider = TokenCipherProvider.initialize("  ", defaultPath);

        assertTrue(provider.isAvailable());
        assertTrue(provider.isAutoGenerated());
    }

    @Test
    void reusesAutoGeneratedKeyAcrossRestarts() {
        Path defaultPath = tempDir.resolve("auto-key");

        var first = TokenCipherProvider.initialize(null, defaultPath);
        byte[] blob = first.cipher().orElseThrow().encrypt("secret".getBytes(StandardCharsets.UTF_8));

        var second = TokenCipherProvider.initialize(null, defaultPath);
        byte[] decrypted = second.cipher().orElseThrow().decrypt(blob);

        assertEquals("secret", new String(decrypted, StandardCharsets.UTF_8));
    }
}
