#!/usr/bin/env bash
#
# Pin the SSH host keys for fogwall's built-in ("provider class default URL") hosts into a checked-in
# known_hosts resource. fogwall verifies upstream SSH host keys against this file (see SshUpstreamTransport),
# so the keys MUST be trustworthy — this script captures them with ssh-keyscan and then verifies each captured
# key against the provider's PUBLISHED fingerprint before writing it. A key that cannot be verified is never
# written.
#
# Maintainer workflow (like generateThirdPartyNotices — run it, review, commit the result):
#   1. Run this script from the repo root.
#   2. GitHub's fingerprints are fetched machine-readably from https://api.github.com/meta and verified
#      automatically. For the other hosts, the script prints the captured fingerprint next to the provider's
#      published-fingerprint documentation URL and requires you to confirm they match (or pass --assume-verified
#      in a trusted, non-interactive build once you have reviewed them).
#   3. Commit the regenerated known_hosts file.
#
# Rotations: host keys change rarely (e.g. GitHub rotated its RSA key in 2023). Because the file is baked into
# the image at a mountable path, operators can also override it without upgrading fogwall — but the shipped
# default should stay current, so re-run this when a provider announces a rotation.
set -euo pipefail

OUT="${OUT:-fogwall-core/src/main/resources/ssh/known_hosts}"
KEY_TYPES="ed25519,rsa,ecdsa"
# Default: write the keys captured by ssh-keyscan, logging each provider's published-fingerprint reference for
# anyone who wants to check — this mirrors how APT keys, release checksums and image digests are actually
# consumed (trust the capture; verify on demand). github.com is always auto-verified against api.github.com/meta.
# Pass --verify for an interactive per-key fingerprint-confirmation gate.
VERIFY=0
[[ "${1:-}" == "--verify" ]] && VERIFY=1

# Provider-class default hosts (see GitHubProvider/GitLabProvider/BitbucketProvider/ForgejoProvider.*).
# host:port  and the provider's published-fingerprint reference for manual verification.
HOSTS=(
  "github.com:22|https://docs.github.com/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints"
  "gitlab.com:22|https://docs.gitlab.com/user/gitlab_com/#ssh-host-keys-fingerprints"
  "bitbucket.org:22|https://support.atlassian.com/bitbucket-cloud/docs/configure-ssh-and-two-step-verification/"
  "codeberg.org:22|https://docs.codeberg.org/security/ssh-fingerprint/"
  "gitea.com:22|https://gitea.com/user/settings/keys"
)

command -v ssh-keyscan >/dev/null || { echo "ssh-keyscan not found" >&2; exit 1; }
command -v ssh-keygen  >/dev/null || { echo "ssh-keygen not found"  >&2; exit 1; }

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# GitHub publishes machine-readable fingerprints — fetch them as the trust anchor for github.com.
github_fps=""
if command -v curl >/dev/null && command -v jq >/dev/null; then
  github_fps="$(curl -fsS https://api.github.com/meta | jq -r '.ssh_key_fingerprints[]' 2>/dev/null || true)"
fi

printf '# fogwall built-in upstream SSH host keys — generated by scripts/pin-ssh-host-keys.sh. DO NOT edit by hand.\n' > "$tmp/known_hosts"

for entry in "${HOSTS[@]}"; do
  hostport="${entry%%|*}"; ref="${entry##*|}"
  host="${hostport%%:*}"; port="${hostport##*:}"
  echo "==> ${host}:${port}"
  scanned="$tmp/${host}.scan"
  ssh-keyscan -T 10 -p "$port" -t "$KEY_TYPES" "$host" 2>/dev/null > "$scanned" || true
  [[ -s "$scanned" ]] || { echo "  ! no keys returned for ${host} — skipped" >&2; continue; }

  verified="$tmp/${host}.verified"; : > "$verified"
  while read -r line; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    fp="$(printf '%s\n' "$line" | ssh-keygen -lf - 2>/dev/null | awk '{print $2}')"
    ok=0
    if [[ "$host" == "github.com" && -n "$github_fps" ]] && grep -qxF "$fp" <<<"$github_fps"; then
      echo "  auto-verified $fp (api.github.com/meta)"
      ok=1
    elif [[ "$VERIFY" == 0 ]]; then
      echo "  captured $fp (published fingerprints: $ref)"
      ok=1
    else
      echo "  fingerprint: $fp"
      echo "  verify against: $ref"
      read -r -p "  Does this fingerprint match the provider's published value? [y/N] " ans < /dev/tty || ans="n"
      [[ "$ans" == "y" || "$ans" == "Y" ]] && ok=1
    fi
    if [[ "$ok" == 1 ]]; then
      printf '%s\n' "$line" >> "$verified"
      echo "  + verified $fp"
    else
      echo "  - REJECTED (unverified) $fp" >&2
    fi
  done < "$scanned"

  cat "$verified" >> "$tmp/known_hosts"
done

mkdir -p "$(dirname "$OUT")"
mv "$tmp/known_hosts" "$OUT"
echo "Wrote $OUT"
